name: Deploy Project to Azure VM

on:
  push:
    branches: [ "main" ]
    paths:
      - 'manifest.json'


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Execute remote SSH commands to sync repo
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.AZURE_VM_HOST }}
        username: ${{ secrets.AZURE_VM_USER }}
        key: ${{ secrets.AZURE_SSH_KEY }}
        script: |
          echo "Conectado con éxito a la VM de Azure. Actualizando repositorio..."
          cd ~/proyecto-data
          git pull origin main --no-rebase
          echo "¡Despliegue completado! Airflow actualizará los DAGs automáticamente."
